#!/bin/sh


for filename in *.cpp 
do
    head=${filename%.*}
    g++ -c -std=c++11 -MMD $filename
    echo "\tg++ -ggdb -O0 -Wall -std=c++11 -c" $filename >> ${head}.d
done


make
echo "build done!"
