#!/bin/sh


for filename in *.cpp 
do
    head=${filename%.*}
    g++ -c -std=c++11 -MMD $filename
    
    if [ $# -ge 1 -a "$1" = "release" ] 
    then
        echo "\tg++  -O3 -Wall -std=c++11 -c" $filename >> ${head}.d
    else
        echo "\tg++ -ggdb3  -O0 -Wall -std=c++11 -c" $filename >> ${head}.d
    fi
done


make
echo "build done!"
